\hypertarget{class_test_failure}{\section{Test\+Failure Class Reference}
\label{class_test_failure}\index{Test\+Failure@{Test\+Failure}}
}


Record of a failed \hyperlink{class_test}{Test} execution.

A \hyperlink{class_test_failure}{Test\+Failure} collects a failed test together with the caught exception.  




{\ttfamily \#include $<$Test\+Failure.\+h$>$}



Collaboration diagram for Test\+Failure\+:
\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\hypertarget{class_test_failure_a0c1b4cee94278814ab7a4ba72f94dac3}{\hyperlink{class_test_failure_a0c1b4cee94278814ab7a4ba72f94dac3}{Test\+Failure} (\hyperlink{class_test}{Test} $\ast$\hyperlink{class_test_failure_a8c7da6077f68897785a69cea6c2b7825}{failed\+Test}, \hyperlink{class_exception}{Exception} $\ast$\hyperlink{class_test_failure_ac12b8f4d9a6a1f130834cf08287d869d}{thrown\+Exception}, bool \hyperlink{class_test_failure_a0b6c1ee50d2186a4918f015d7879e8dd}{is\+Error})}\label{class_test_failure_a0c1b4cee94278814ab7a4ba72f94dac3}

\begin{DoxyCompactList}\small\item\em Constructs a \hyperlink{class_test_failure}{Test\+Failure} with the given test and exception. \end{DoxyCompactList}\item 
\hypertarget{class_test_failure_a117d2f3616bed325e97b0ac2fe7d9e4b}{virtual \hyperlink{class_test_failure_a117d2f3616bed325e97b0ac2fe7d9e4b}{$\sim$\+Test\+Failure} ()}\label{class_test_failure_a117d2f3616bed325e97b0ac2fe7d9e4b}

\begin{DoxyCompactList}\small\item\em Deletes the owned exception. \end{DoxyCompactList}\item 
\hypertarget{class_test_failure_a8c7da6077f68897785a69cea6c2b7825}{virtual \hyperlink{class_test}{Test} $\ast$ \hyperlink{class_test_failure_a8c7da6077f68897785a69cea6c2b7825}{failed\+Test} () const }\label{class_test_failure_a8c7da6077f68897785a69cea6c2b7825}

\begin{DoxyCompactList}\small\item\em Gets the failed test. \end{DoxyCompactList}\item 
\hypertarget{class_test_failure_ac12b8f4d9a6a1f130834cf08287d869d}{virtual \hyperlink{class_exception}{Exception} $\ast$ \hyperlink{class_test_failure_ac12b8f4d9a6a1f130834cf08287d869d}{thrown\+Exception} () const }\label{class_test_failure_ac12b8f4d9a6a1f130834cf08287d869d}

\begin{DoxyCompactList}\small\item\em Gets the thrown exception. Never {\ttfamily N\+U\+L\+L}. \end{DoxyCompactList}\item 
\hypertarget{class_test_failure_a0da7fc89d01c8b42c96cd0542eba58eb}{virtual \hyperlink{class_source_line}{Source\+Line} \hyperlink{class_test_failure_a0da7fc89d01c8b42c96cd0542eba58eb}{source\+Line} () const }\label{class_test_failure_a0da7fc89d01c8b42c96cd0542eba58eb}

\begin{DoxyCompactList}\small\item\em Gets the failure location. \end{DoxyCompactList}\item 
\hypertarget{class_test_failure_a0b6c1ee50d2186a4918f015d7879e8dd}{virtual bool \hyperlink{class_test_failure_a0b6c1ee50d2186a4918f015d7879e8dd}{is\+Error} () const }\label{class_test_failure_a0b6c1ee50d2186a4918f015d7879e8dd}

\begin{DoxyCompactList}\small\item\em Indicates if the failure is a failed assertion or an error. \end{DoxyCompactList}\item 
\hypertarget{class_test_failure_af2f5978f08aa97106acdb09a57807a0e}{virtual std\+::string \hyperlink{class_test_failure_af2f5978f08aa97106acdb09a57807a0e}{failed\+Test\+Name} () const }\label{class_test_failure_af2f5978f08aa97106acdb09a57807a0e}

\begin{DoxyCompactList}\small\item\em Gets the name of the failed test. \end{DoxyCompactList}\item 
\hypertarget{class_test_failure_aeba45f44e148dc01146c615da438ab91}{virtual \hyperlink{class_test_failure}{Test\+Failure} $\ast$ {\bfseries clone} () const }\label{class_test_failure_aeba45f44e148dc01146c615da438ab91}

\item 
\hypertarget{class_test_failure_a0ecf7ad4ab673974d30d10ffb2b01790}{{\bfseries Test\+Failure} (\hyperlink{class_test}{Test} $\ast$\hyperlink{class_test_failure_a8c7da6077f68897785a69cea6c2b7825}{failed\+Test}, \hyperlink{class_exception}{Exception} $\ast$\hyperlink{class_test_failure_ac12b8f4d9a6a1f130834cf08287d869d}{thrown\+Exception}, bool \hyperlink{class_test_failure_a0b6c1ee50d2186a4918f015d7879e8dd}{is\+Error})}\label{class_test_failure_a0ecf7ad4ab673974d30d10ffb2b01790}

\item 
\hypertarget{class_test_failure_a35aa1b953feff8635c832a53d3c6946d}{virtual \hyperlink{class_test}{Test} $\ast$ {\bfseries failed\+Test} () const }\label{class_test_failure_a35aa1b953feff8635c832a53d3c6946d}

\item 
\hypertarget{class_test_failure_a8e60e0c1ea068bef6c546d20d8260400}{virtual \hyperlink{class_exception}{Exception} $\ast$ {\bfseries thrown\+Exception} () const }\label{class_test_failure_a8e60e0c1ea068bef6c546d20d8260400}

\item 
\hypertarget{class_test_failure_aa3c6a076dca224d7e440212cfd127305}{virtual \hyperlink{class_source_line}{Source\+Line} {\bfseries source\+Line} () const }\label{class_test_failure_aa3c6a076dca224d7e440212cfd127305}

\item 
\hypertarget{class_test_failure_a23b25cf3452b3ab7dc84c70664f13ff0}{virtual bool {\bfseries is\+Error} () const }\label{class_test_failure_a23b25cf3452b3ab7dc84c70664f13ff0}

\item 
\hypertarget{class_test_failure_aca471a29c01d3c5e4d439aadbb1825bf}{virtual std\+::string {\bfseries failed\+Test\+Name} () const }\label{class_test_failure_aca471a29c01d3c5e4d439aadbb1825bf}

\item 
\hypertarget{class_test_failure_a0f0c86f12431ea8adde3e70e0cb52db7}{virtual \hyperlink{class_test_failure}{Test\+Failure} $\ast$ {\bfseries clone} () const }\label{class_test_failure_a0f0c86f12431ea8adde3e70e0cb52db7}

\end{DoxyCompactItemize}
\subsection*{Protected Attributes}
\begin{DoxyCompactItemize}
\item 
\hypertarget{class_test_failure_ab74a25c97a86cff454902aeeb8fe9b0e}{\hyperlink{class_test}{Test} $\ast$ {\bfseries m\+\_\+failed\+Test}}\label{class_test_failure_ab74a25c97a86cff454902aeeb8fe9b0e}

\item 
\hypertarget{class_test_failure_a4582e2503281fb614819fcb9d96f3b7a}{\hyperlink{class_exception}{Exception} $\ast$ {\bfseries m\+\_\+thrown\+Exception}}\label{class_test_failure_a4582e2503281fb614819fcb9d96f3b7a}

\item 
\hypertarget{class_test_failure_abf258e5bec289b51fb13147a62b8b75d}{bool {\bfseries m\+\_\+is\+Error}}\label{class_test_failure_abf258e5bec289b51fb13147a62b8b75d}

\end{DoxyCompactItemize}


\subsection{Detailed Description}
Record of a failed \hyperlink{class_test}{Test} execution.

A \hyperlink{class_test_failure}{Test\+Failure} collects a failed test together with the caught exception. 

\hyperlink{class_test_failure}{Test\+Failure} assumes lifetime control for any exception passed to it. 

The documentation for this class was generated from the following files\+:\begin{DoxyCompactItemize}
\item 
assimp/assimp-\/3.\+1.\+1/contrib/cppunit-\/1.\+12.\+1/include/cppunit/Test\+Failure.\+h\item 
assimp/assimp-\/3.\+1.\+1/contrib/cppunit-\/1.\+12.\+1/src/cppunit/Test\+Failure.\+cpp\end{DoxyCompactItemize}
