digraph "TestCase::runTest"
{
  edge [fontname="Helvetica",fontsize="10",labelfontname="Helvetica",labelfontsize="10"];
  node [fontname="Helvetica",fontsize="10",shape=record];
  rankdir="LR";
  Node1 [label="TestCase::runTest",height=0.2,width=0.4,color="black", fillcolor="grey75", style="filled", fontcolor="black"];
  Node1 -> Node2 [dir="back",color="midnightblue",fontsize="10",style="solid",fontname="Helvetica"];
  Node2 [label="TestCase::run",height=0.2,width=0.4,color="black", fillcolor="white", style="filled",URL="$class_test_case.html#ac3011d91e8a2d38162f72888d2ecafd7",tooltip="Run the test and catch any exceptions that are triggered by it. "];
  Node1 -> Node3 [dir="back",color="midnightblue",fontsize="10",style="solid",fontname="Helvetica"];
  Node3 [label="TestCaseDecorator::\lrunTest",height=0.2,width=0.4,color="black", fillcolor="white", style="filled",URL="$class_test_case_decorator.html#ad083ca55ff2e7f1f3f442364aa1dde66",tooltip="FIXME: this should probably be pure virtual. "];
  Node3 -> Node4 [dir="back",color="midnightblue",fontsize="10",style="solid",fontname="Helvetica"];
  Node4 [label="ExceptionTestCaseDecorator\l::runTest",height=0.2,width=0.4,color="black", fillcolor="white", style="filled",URL="$class_exception_test_case_decorator.html#a3f78294d459a94f55413162d814f291d",tooltip="Checks that the expected exception is thrown by the decorated test. is thrown. "];
}
